""" 
Sources:
    hedge_weasel_words:  Hedging, Weasel Words, and Truthiness in Scientific Writing, Douglas E. Ott, 10.4293/JSLS.2018.00063
    hedge_words: https://github.com/words/hedges/blob/master/data.txt

"""

hedge_weasel_words = ['A bit', 'A lot', 'About', 'Abstract', 'Abundant',
                     'Acceptable','According to', 'Actually', 'Aim', 'Alleged', 
                     'Almost', 'Always','Ambiguity', 'Ambiguous', 'Ample', 
                     'Apparent', 'Apparently', 'Appear', 'Appearance', 'Approached',
                     'Approaching', 'Approximately', 'Apt', 'Arguably', 'Argue',
                     'Around', 'As long as', 'Association', 'Assume', 'Assumed', 
                     'Assuming', 'Average', 'Barely', 'Basically', 'Belief', 'Believe',
                     'Best', 'Big', 'Borderline', 'Broad', 'Broadly', 'But','Certain', 
                     'Certianly', 'Chiefly', 'Circumstantial', 'Claim', 'Clearly', 
                     'Common', 'Commonly', 'Comparatively', 'Conceivably', 'Conclude',
                     'Conditional', 'Conjecture', 'Connotes', 'Considerable', 'Consistent',
                     'Consistent with', 'Copious', 'Correlated', 'Correlates with', 'Could',
                     'Could also', 'Cloud be', 'Countless', 'Customarily', 'Customary', 
                     'Denotes', 'Despite', 'Despite limitation', 'Despite this', 'Doubt',
                     'Dramatically', 'Drawback', 'Easy', 'Efficent', 'Essentially', 
                     'Estimate', 'Estimated', 'Estimation', 'Etcetra', 'Even if', 
                     'Evidently', 'Expect', 'Extensive', 'Extrapolate', 'Extrapolation',
                     'Fairly', 'Fast', 'Favorable', 'Favorable trend', 'Feasible',
                     'Feasibly', 'Few', 'Fewer', 'Figurative', 'Figuratively',
                     'Flexible', 'Foresee', 'Frequent', 'Frenquently', 'General', 'Gererous',
                     'Good', 'Guess', 'Hardly', 'Has a role', 'Helps', 'Highly', 'However',
                     'Hypothetical', 'I suggest', 'If', 'In other instance', 'Implication',
                     'Implied', 'Implies', 'In general', 'In our hands', 'In some ways', 
                     'Inclination', 'Indeed', 'Indicate', 'Indication', 'Indicative', 'Inference',
                     'Infers', 'Innumerable', 'Inspite of shortcomings', 'Instead', 'Is like',
                     'Judgement', 'Kind of', 'Large', 'Largely', 'Leaning', 'Less', 'Likelihood',
                     'Likely', 'Link', 'Linked', 'Literally', 'Looks', 'Loosely',
                     'Lots', 'Mainly', 'Mainstream', 'Mainstains', 'Many', 'Marginal',
                     'Maximize', 'May', 'May be', 'Maybe', 'Means', 'Mere', 'Merely',
                     'Might', 'Mild trend', 'Minimize', 'More', 'More or less', 'Most',
                     'Mostly', 'Much', 'Must', 'Myriad', 'Naturally', 'Nearly', 'Never',
                     'Nevertheless', 'Normal', 'Normally', 'Not clear', 'Not quite', 
                     'Numerous', 'Obvious', 'Obviously', 'Of course', 'Often', 'Opinion',
                     'Optimal', 'Optimize', 'Ordinarily', 'Our results', 
                     'Partially', 'Perception', 'Pereceived', 'Perfect', 'Perfectly',
                     'Perhaps', 'Plausible', 'Plentiful', 'Posit', 'Possible', 'Possibly',
                     'Postulate', 'Postulated', 'Potentially', 'Potential', 'Practically',
                     'Predict', 'Predominant', 'Predominantly', 'Presumably', 'Presume', 
                     'Presumed', 'Presumption', 'Prevailing', 'Prevalent', 'Prinicipally',
                     'Provided', 'Propose', 'Probably', 'Probably', 'Probable', 'Probability',
                     'Provided', 'Provisional', 'Putative', 'Quite', 'Rapid', 'Rarely',
                     'Rather', 'Reasonably', 'Regularly', 'Rather', 'Reasonably', 'Regularly',
                     'Relatively', 'Reliable', 'Reportedly', 'Represemts', 'Robust',
                     'Roughly', 'Routine', 'Scarely', 'Secure', 'Seemingly', 'Seems',
                     'Seen as', 'Several', 'Severe', 'Shortcomings', 'Should', 'Signifies',
                     'Sizeable', 'Slightly', 'Slow', 'Some', 'Somehow', 'Somehow somewhat',
                     'Someway', 'Somewhat', 'Speculate', 'Speculation', 'Speculation',
                     'Speculative', 'Standard', 'Statistical trend', 'Still', 'Strongly',
                     'Strongly suggests', 'Substantial', 'Sufficient', 'Suggest',
                     'Suggestion', 'Suggestive', 'Suggests', 'Suppose', 'Supposed',
                     'Supposition', 'Symbolic', 'Tend', 'Tendency', 'Tending',
                     'Tentative', 'Tentatively', 'That being said', 'The best',
                     'The fact that', 'Then the opposite is also possible', 'Theoretical',
                     'Theoretically', 'Though', 'To my knowledge', 'Traditional',
                     'Trend', 'Trending', 'Typical', 'Typically', 'Ultimately', 
                     'Uncertain', 'Unless', 'Unlikely', 'Usual', 'Usually', 'Various',
                     'Very closely', 'Very likely', 'Viewed in this way', 'Virtually',
                     'We infer', 'We propse', 'Weakly', 'Wide', 'Widespread', 
                     'With all due respect', 'Would', 'Would appear', 'Yet']


hedge_words =   ['largely', 'generally', 'often', 'rarely', 'sometimes', 'frequently',
                 'occasionally', 'seldom', 'usually', 'most', 'several', 'some',
                 'almost', 'practically', 'apparently', 'virtually', 'basically',
                 'approximately', 'roughly', 'somewhat', 'somehow', 'partially',
                 'actually', 'like', 'something','someone', 'somebody', 'somewhere',
                 'think', 'thinks', 'thought', 'believe', 'believed', 'believes', 'consider',
                 'considers', 'considered', 'assume', 'assumes', 'assumed', 'understand',
                 'understands', 'understood','find', 'found', 'finds', 'appear', 
                 'appears', 'appeared', 'seem', 'seems', 'seemed', 'suppose', 
                 'supposes', 'supposed', 'guess', 'guesses', 'guessed', 'estimate',
                 'estimates', 'estimated', 'speculate', 'speculates', 'speculated',
                 'suggest', 'suggests', 'suggested', 'may', 'could', 'should',
                 'might', 'surely', 'probably', 'likely', 'maybe', 'perhaps', 'unsure',
                 'probable', 'unlikely', 'possibly', 'possible', 'read', 'say', 'says',
                 'looks like', 'look like', 'don\'t know', 'necessarily', 'kind of', 'much',
                 'bunch', 'couple', 'few', 'little', 'really', 'and all that', 
                 'and so forth', 'et cetera', 'in my mind', 'in my opinion', 
                 'their impression', 'my impression', 'in my understanding', 
                 'my thinking is', 'my understanding is', 'in my view',
                 'if i\'m understanding you correctly', 'something or other', 
                 'so far', 'at least', 'about', 'around', 'can', 'effectively', 
                 'evidently', 'fairly', 'hopefully', 'in general', 'mainly', 
                 'more or less', 'mostly', 'overall', 'presumably', 'pretty strong',
                 'pretty weak', 'pretty', 'quite clearly', 'quite', 'rather', 
                 'sort of', 'supposedly', 'tend', 'appear to be', 'doubt','be sure', 
                 'indicate', 'will', 'must', 'would', 'certainly', 'definitely', 
                 'clearly', 'conceivably', 'certain', 'definite', 'clear',
                 'assumption', 'possibility', 'probability', 'many', 'almost never',
                 'improbable', 'always', 'rare', 'consistent with', 
                 'doubtful', 'suggestive', 'diagnostic', 'inconclusive', 'apparent',
                 'alleged', 'allege', 'a bit', 'presumable' ]
 
stop_words = ['Mrs.', 'Ms.', 'Say', 'Washington']

sample_text = "Serco's Office of Partner Relations (OPR) helps facilitate our aggressive small business utilization and growth strategies. Through the OPR, Serco mentors four local small businesses under formal Mentor Protégé Agreements: Three sponsored by DHS (Base One Technologies, TSymmetry, Inc., and HeiTech Services, Inc.,) and the fourth sponsored by GSA (DKW Communications, Inc.). Serco and HeiTech Services were awarded the 2007 DHS Mentor Protégé Team Award for exceeding our mentoring goals. The NVC also preprocesses the chief of mission (COM) application required for the filing of a petition for a Special Immigrant Visa (SIV). Such visas, for foreign nationals who have performed services for the U.S. government in Iraq and Afghanistan, require COM concurrence before the applicant can file a petition with USCIS. The NVC collects the requisite documents from such applicants and, when complete, forwards the package to the U.S. embassies in Baghdad or Kabul for COM approval"
